# workflow name
name: Generate release-artifacts

# on events
on:
 release:
   types: 
       - created

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          #sudo apt-get update
          #sudo apt-get upgrade -y
          sudo apt-get install python3-virtualenv build-essential
          sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev -y
          sudo apt-get install golang wixl msitools -y
          sudo pip install hitchkey
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Build multiarch
        run: hk multiarch
    
      - name: Upload build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./dist/*"
